openapi: 3.0.0
info:
  title: CreateCustomer
  version: '1.0'
servers:
  - url: 'https://dev.ipactsolutions.com'
    description: DEV
paths:
  /customers:
    post:
      summary: ''
      operationId: post-customers
      responses:
        '200':
          description: OK
components:
  schemas: {}
