openapi: 3.0.0
info:
  title: ItemList
  version: '1.0'
  description: 'List of Items '
servers:
  - url: 'http://localhost:8080/scm-rest/api'
    description: Staging
paths:
  /items:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-items
      description: Get Items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                result:
                  type: object
                  properties:
                    total:
                      type: integer
                    rows:
                      type: object
                    supplierName:
                      type: string
                    hsnCode:
                      type: string
                    supplierId:
                      type: number
                    supplierPartNo:
                      type: string
                    description:
                      type: string
                    currencySymbol:
                      type: string
                    entityId:
                      type: number
                    itemNo:
                      type: string
                    categoryCode:
                      type: string
                    itemId:
                      type: number
                    uom:
                      type: string
                    price:
                      type: number
                    entityName:
                      type: string
                    mfr:
                      type: string
                    currency:
                      type: integer
            examples:
              Item List Response: {}
          application/xml:
            schema:
              type: object
              properties: {}
      parameters:
        - schema:
            type: integer
          in: query
          name: current
        - schema:
            type: integer
          in: query
          name: rowCount
        - schema:
            type: string
          in: query
          name: searchBy
        - schema:
            type: string
          in: query
          name: search
        - schema:
            type: string
          in: query
          name: Authorization
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
security:
  - API Key - 1: []
