openapi: 3.0.0
info:
  title: ItemList
  version: '1.0'
  description: 'List of Items '
servers:
  - url: 'http://localhost:8080/scm-rest/api'
    description: Staging
paths:
  /items:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-items
      description: Get Items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              Item List Response: {}
      parameters:
        - schema:
            type: integer
          in: query
          name: current
        - schema:
            type: integer
          in: query
          name: rowCount
        - schema:
            type: string
          in: query
          name: searchBy
        - schema:
            type: string
          in: query
          name: search
        - schema:
            type: string
          in: query
          name: Authorization
    parameters: []
components:
  schemas: {}
  securitySchemes: {}
security:
  - API Key - 1: []
