openapi: 3.0.0
info:
  title: Authenticate
  version: '1.0'
  description: ''
servers:
  - url: 'https://dev.ipactsolutions.com/scm-rest/api'
    description: Dev
paths:
  /authenticate:
    post:
      summary: Authenticate-API
      operationId: post-authenticate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  result:
                    type: object
                    properties:
                      accessToken:
                        type: string
                      userId:
                        type: string
                      profileId:
                        type: string
                      name:
                        type: string
                      email:
                        type: string
                      preferences:
                        type: object
                        properties:
                          Customer:
                            type: object
                            properties:
                              view:
                                type: string
                              edit:
                                type: string
                              create:
                                type: string
                              delete:
                                type: string
                          Sales Order:
                            type: object
                            properties:
                              view:
                                type: string
                              edit:
                                type: string
                              create:
                                type: string
                              delete:
                                type: string
              examples:
                Auth Response:
                  value:
                    status: success
                    result:
                      accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJzZWN1cmUtc2NtLWFwaSIsImF1ZCI6InNlY3VyZS1zY20tYXBwIiwic3ViIjoiS0xNX05ld0FkbWluIiwiZXhwIjoxNjIyNDUzNjA3LCJsYW5nIjoiZW4iLCJlbnRpdHlJZExpc3QiOiIyLDQiLCJ2aWV3SWRzIjoiMCIsIm9yZ0lkIjoiMiIsInVzZXJJZCI6IjIiLCJzdXBwbGllcklkIjoiMCJ9.qGZydITNHTOAIUDkbq55n-rMqCK9eQl1ExCaXd-v5rT5leyIe7MsJ9Ql64sNf4sQ4-ac1oZv3SbO1D0O1dEoTQ
                      userId: '2'
                      profileId: '2'
                      name: KLM
                      email: vidya@menigmainfosystem.com
                      preferences:
                        salesOrder:
                          view: true
                          edit: true
                          create: true
                          delete: false
                        customer:
                          view: true
                          edit: true
                          create: true
                          delete: false
            application/xml:
              schema:
                type: object
                properties:
                  '':
                    type:
                      - string
                      - object
              examples:
                example-1: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
            examples:
              Credientials:
                value:
                  username: KLM_NewAdmin
                  password: Abcd@123
components:
  schemas: {}
